### ISSUE TITLE
Could not find stored procedure 'sys.sp_MS_marksystemobject'.

### ISSUE THREAD

**Issue by francesco1119** [SQLBek/sp_helpExpandView#3]
I just tried to install sp_helpExpandView on master on Azure SQL Database and it returns: 

```
Msg 2812, Level 16, State 62, Line 466
Could not find stored procedure 'sys.sp_MS_marksystemobject'.

Completion time: 2022-09-20T10:10:25.9941264+02:00
```

Is sp_helpExpandView compatible with Azure SQL Database?

**Comment by SQLBek** [comment]
So I've never tested this on Azure SQL Database, but I see no reason why it should not work.  

Just comment out the line that calls out to sys.sp_MS_marksystemobject - all that does is allow you to call the procedure from any database (on a regular instance of SQL Server).
